import { expect, test } from '@playwright/test';
import { resetE2eState } from '../../apps/api/src/database/reset-e2e';

test.setTimeout(120_000);
test.use({ launchOptions: { args: process.env.TERRAIN_GPU === '1' && process.platform === 'win32' ? ['--use-angle=d3d11'] : [] } });
test('cosmological pause, rotating torus picking and local return preserve navigation without commands', async ({ page }, info) => {
  await resetE2eState();
  const errors: string[] = [], geography: string[] = [], commands: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('response', r => { if (r.url().endsWith('/terrain/overview')) geography.push(r.url()); });
  await page.goto('/');
  await page.getByLabel('Adresse e-mail').fill('player@arbestra.local');
  await page.getByLabel('Mot de passe').fill('arbestra');
  await page.getByRole('button', { name: 'Se connecter' }).click();
  await page.getByRole('link', { name: /Monde de l'Aube/ }).click();
  const canvas = page.getByTestId('village-canvas');
  await expect(canvas).toBeVisible({ timeout: 40_000 });
  page.on('request', r => { if (r.method() === 'POST' && r.url().includes('/api/')) commands.push(r.url()); });
  await page.getByRole('button', { name: 'Cosmologie · debug' }).click();
  await expect(page.getByRole('region', { name: 'Laboratoire cosmologique' })).toBeVisible();
  await page.getByRole('button', { name: 'Pause cosmologique' }).click();
  const phase = async () => JSON.parse(await canvas.getAttribute('data-cosmology') ?? '{}') as {
    phase: number; torusPhase: number; sunPhase: number; rotationPeriodMs: number; paused: boolean;
  };
  await expect.poll(async () => (await phase()).paused).toBe(true);
  const frozen = (await phase()).phase;
  await page.waitForTimeout(1200);
  expect((await phase()).phase).toBe(frozen);
  await page.getByLabel('Phase cosmologique').focus();
  await page.getByLabel('Phase cosmologique').press('Home');
  await expect.poll(async () => (await phase()).phase).toBe(0);
  await page.getByLabel('Phase cosmologique').press('PageUp');
  await expect.poll(async () => (await phase()).phase).toBeGreaterThan(0);
  const chosenPhase = (await phase()).phase;
  expect((await phase()).torusPhase).toBeCloseTo(chosenPhase * 3);
  expect((await phase()).sunPhase).toBeCloseTo(chosenPhase * 2);
  await page.getByLabel('Durée de rotation').fill('60');
  await expect.poll(async () => (await phase()).rotationPeriodMs).toBe(60_000);
  await expect(page.getByText('Tore : 60 s · Soleil : 90 s · Cycle combiné : 180 s')).toBeVisible();
  await page.getByLabel('Durée de rotation').fill('120');
  await expect.poll(async () => (await phase()).rotationPeriodMs).toBe(120_000);
  await page.getByRole('button', { name: 'Monde torique' }).click();
  await expect(canvas).toHaveAttribute('data-view-mode', 'world', { timeout: 60_000 });
  await expect(canvas).toHaveAttribute('data-cloud-cover', '0');
  const cameraState = async () => JSON.parse(await canvas.getAttribute('data-world-camera') ?? '{}') as {
    sticky: boolean; screen: number[]; position: number[]; alpha: number; beta: number; radius: number;
  };
  const attached = await cameraState(); expect(attached.sticky).toBe(true);
  expect(attached.screen[0]).toBeCloseTo(.5, 3); expect(attached.screen[1]).toBeCloseTo(.5, 3);
  expect(attached.radius).toBeGreaterThan(0); expect(attached.radius).toBeLessThan(2);
  await page.getByLabel('Phase cosmologique').press('PageUp');
  await expect.poll(async () => (await cameraState()).position).not.toEqual(attached.position);
  const rotated = await cameraState();
  expect(rotated.screen[0]).toBeCloseTo(attached.screen[0]!, 3);
  expect(rotated.screen[1]).toBeCloseTo(attached.screen[1]!, 3);
  expect([rotated.alpha, rotated.beta, rotated.radius]).toEqual([attached.alpha, attached.beta, attached.radius]);
  await page.getByLabel('Phase cosmologique').press('PageDown');
  await expect.poll(async () => (await phase()).phase).toBeCloseTo(chosenPhase);
  const renderer = await canvas.evaluate(el => {
    const gl = (el as HTMLCanvasElement).getContext('webgl2') ?? (el as HTMLCanvasElement).getContext('webgl');
    const extension = gl?.getExtension('WEBGL_debug_renderer_info');
    return extension ? String(gl!.getParameter(extension.UNMASKED_RENDERER_WEBGL)) : 'unavailable';
  });
  console.log(`Cosmology renderer (${info.project.name}): ${renderer}`);
  await page.screenshot({ path: `test-results/cosmology-debug-${info.project.name}.png` });
  await page.getByRole('button', { name: 'Cosmologie · debug' }).click();
  const bounds = (await canvas.boundingBox())!;
  let chosen: string | null = null;
  for (const [x, y] of [[.5, .4], [.72, .68], [.3, .55], [.5, .72]]) {
    await page.mouse.click(bounds.x + bounds.width * x, bounds.y + bounds.height * y);
    chosen = await canvas.getAttribute('data-world-pick');
    if (chosen && chosen !== 'none') break;
  }
  expect(chosen).toMatch(/^\d+,\d+$/);
  await page.getByRole('button', { name: 'Voir cette région' }).click();
  await expect.poll(() => canvas.getAttribute('data-view-target')).toBe(chosen);
  await page.getByRole('button', { name: 'Monde torique' }).click();
  await expect(canvas).toHaveAttribute('data-view-mode', 'world');
  await expect(canvas).toHaveAttribute('data-cloud-cover', '0');
  await page.getByRole('button', { name: 'Cosmologie · debug' }).click();
  await page.getByRole('button', { name: 'Profil du huit' }).click();
  await page.waitForTimeout(400);
  await page.screenshot({ path: `test-results/cosmology-profile-${info.project.name}.png` });
  await expect(page.getByRole('button', { name: 'Apercevoir le Chat' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Cosmologie · debug' }).click();
  await page.waitForTimeout(400);
  await expect.poll(async () => (await cameraState()).sticky).toBe(true);
  await page.screenshot({ path: `test-results/cosmology-sky-${info.project.name}.png` });
  await page.getByRole('button', { name: 'Mon village' }).click();
  await expect(canvas).toHaveAttribute('data-view-mode', 'village');
  expect((await phase()).paused).toBe(false);
  expect((await phase()).rotationPeriodMs).toBe(28_800_000);
  expect(geography).toHaveLength(1);
  expect(commands).toEqual([]); expect(errors).toEqual([]);
});
