import {useEffect,useMemo,useState} from 'react';
import type {GeneratedLandscape} from '@arbestra/contracts';
import {sampleWorldGeography} from '@arbestra/contracts/world-geography';
import {PreviewScene,type PreviewLayer,type PreviewStats} from './PreviewScene';
import './world-generator.css';
import './terrain-study.css';
const canonical=(value:number,size:number)=>Number.isFinite(value)?Number((((value%size)+size)%size).toFixed(1))%size:0;
function initial(){const p=new URLSearchParams(location.search);return {world:['t1-base','t1-alpha','t1-alpha512'].includes(p.get('world')??'')?p.get('world')!:'t1',x:canonical(Number(p.get('x')??(p.get('world')==='t1-alpha512'?140:70)),p.get('world')==='t1-alpha512'?512:256),y:canonical(Number(p.get('y')??(p.get('world')==='t1-alpha512'?90:45)),p.get('world')==='t1-alpha512'?256:128),view:['local','map'].includes(p.get('view')??'')?p.get('view')!:'torus',layer:p.get('layer')==='altitude'?'altitude' as const:'terrain' as const,water:p.get('water')==='1'||(p.get('water')!=='0'&&p.get('world')!=='t1-base'),chunks:p.get('chunks')!=='0',coordinates:p.get('coordinates')==='1'};}
const places=[{name:'Montée F4–F3',x:174,y:100},{name:'Massif E3–F3',x:155,y:89},{name:'Bassin H/A3',x:0,y:80},{name:'Bassin H1–B1',x:16,y:16},{name:'Trois bras G1–G2',x:213,y:31},{name:'Coude E4',x:146,y:108},{name:'Passage F1',x:177,y:8},{name:'Chaîne A',x:70,y:45},{name:'Chaîne B',x:171,y:81},{name:'Creux C',x:120,y:80},{name:'Creux D',x:213,y:31},{name:'Plaine',x:80,y:10}];
export function TerrainStudy(){
 const [locationState,setLocation]=useState(initial),[data,setData]=useState<GeneratedLandscape|null>(null),[error,setError]=useState(''),[copied,setCopied]=useState(false);
 const [draft,setDraft]=useState({x:String(locationState.x),y:String(locationState.y)}),[wire,setWire]=useState(false),[stats,setStats]=useState<PreviewStats|null>(null);
 useEffect(()=>{const abort=new AbortController();fetch('/studies/'+locationState.world+'.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw Error('Chargement du monde témoin impossible');return r.json();}).then(setData).catch(e=>{if(!abort.signal.aborted)setError(String(e));});return()=>abort.abort();},[locationState.world]);
 useEffect(()=>{const p=new URLSearchParams({world:locationState.world,view:locationState.view,x:String(locationState.x),y:String(locationState.y),layer:locationState.layer,water:locationState.water?'1':'0',chunks:locationState.chunks?'1':'0',coordinates:locationState.coordinates?'1':'0'});history.replaceState(null,'','/terrain-study?'+p);setCopied(false);},[locationState]);
 const width=locationState.world==='t1-alpha512'?512:256,height=width/2,scale=width/256;
 const select=(x:number,y:number,local=false)=>{const point={x:canonical(x,width),y:canonical(y,height)};setDraft({x:String(point.x),y:String(point.y)});setLocation(s=>({...s,...point,view:local?'local':s.view}));};
 const copyLink=async()=>{try{if(!navigator.clipboard)throw Error('clipboard unavailable');await navigator.clipboard.writeText(location.href);setCopied(true);}catch{setError('Copie indisponible : copie le lien affiché ci-dessous.');}};
 const displayed=useMemo(()=>data&&locationState.water?{...data,geography:{...data.geography!,study:{...data.geography!.study!,waterLevel:0}}}:data,[data,locationState.water]);
 const sector=String.fromCharCode(65+Math.floor(locationState.x/32))+(Math.floor(locationState.y/32)+1);
 const altitude=data?sampleWorldGeography(data.geography!,locationState.x,locationState.y).elevation*4:null;
 return <main className="terrain-study" data-study-world={locationState.world}><header><div><p>ARBESTRA · MONDE TÉMOIN T1</p><h1>{locationState.world==='t1-alpha512'?'Alpha 512 × 256':locationState.world==='t1-base'?'Base sauvegardée':locationState.world==='t1-alpha'?'Monde alpha validé':'Plateaux et pierre — variante'}</h1></div><a href="/world-generator">World generator</a></header>
 <p>{width} × {height} cases · {width/32*height/32} chunks de 32 × 32 · {locationState.world==='t1-base'?'plaines de base à +1 unité':'plateaux bas entre +0,5 et +3 unités'} · {locationState.water?'eau au niveau 0':'sans eau'}. X fait le tour de l’anneau ; Y fait le tour du tube. Les bords opposés se rejoignent.</p>
 <nav className="study-toolbar" aria-label="Versions">{[{id:'t1-alpha512',name:'Alpha 512 × 256'},{id:'t1-alpha',name:'Monde alpha validé'},{id:'t1-base',name:'Base sauvegardée'},{id:'t1',name:'Variante plateaux et pierre'}].map(v=><a key={v.id} aria-current={locationState.world===v.id?'page':undefined} href={'/terrain-study?'+new URLSearchParams({world:v.id,view:locationState.view,x:String(locationState.x*(v.id==='t1-alpha512'?512:256)/width),y:String(locationState.y*(v.id==='t1-alpha512'?256:128)/height),layer:locationState.layer,water:locationState.water?'1':'0',chunks:locationState.chunks?'1':'0',coordinates:locationState.coordinates?'1':'0'})}>{v.name}</a>)}</nav>
 <nav className="study-toolbar" aria-label="Vues">{[{id:'torus',name:'Tore'},{id:'map',name:'Carte à plat'},{id:'local',name:'Inspection locale'}].map(v=><button key={v.id} aria-pressed={locationState.view===v.id} onClick={()=>setLocation(s=>({...s,view:v.id}))}>{v.name}</button>)}
 <label>Lecture <select aria-label="Lecture" value={locationState.layer} onChange={e=>setLocation(s=>({...s,layer:e.target.value as 'terrain'|'altitude'}))}><option value="terrain">Terrain et forêt</option><option value="altitude">Relief sans arbres</option></select></label>
 <label><input type="checkbox" checked={locationState.chunks} onChange={e=>setLocation(s=>({...s,chunks:e.target.checked}))}/>Chunks serveur (32 × 32)</label><label><input type="checkbox" checked={locationState.coordinates} onChange={e=>setLocation(s=>({...s,coordinates:e.target.checked}))}/>Repères de coordonnées</label><label><input type="checkbox" checked={locationState.water} onChange={e=>setLocation(s=>({...s,water:e.target.checked}))}/>Eau au niveau 0</label><label><input type="checkbox" checked={wire} onChange={e=>setWire(e.target.checked)}/>Maillage</label></nav>
 <form className="study-toolbar" onSubmit={e=>{e.preventDefault();select(Number(draft.x),Number(draft.y),true);}}>
 <label>X <input aria-label="X" type="number" step="0.1" value={draft.x} onChange={e=>setDraft(s=>({...s,x:e.target.value}))}/></label><label>Y <input aria-label="Y" type="number" step="0.1" value={draft.y} onChange={e=>setDraft(s=>({...s,y:e.target.value}))}/></label><button type="submit">Aller à ces coordonnées</button>
 <button type="button" onClick={()=>void copyLink()}>{copied?'Lien copié':'Copier le lien de cette position'}</button></form>
 <div className="study-toolbar">{places.map(p=><button key={p.name} onClick={()=>select(p.x*scale,p.y*scale,true)}>{p.name} ({p.x*scale}, {p.y*scale})</button>)}{locationState.world!=='t1-base'&&<button onClick={()=>select(32*scale,64*scale,true)}>Mer agrandie H–C</button>}{data?.stoneSites?.[0]&&<button onClick={()=>select(data.stoneSites![0]!.x,data.stoneSites![0]!.y,true)}>Pierre en plaine</button>}</div>
 <p className="study-location" data-study-location>Secteur <strong>{sector}</strong> · X={locationState.x} · Y={locationState.y} · altitude {altitude?.toFixed(2)??'…'} unités <span>— une unité = ¼ de case</span></p>
 {error&&<p role="alert">{error}</p>}
 {displayed?<PreviewScene candidateKey={locationState.world+(locationState.water?'-water':'-dry')} data={displayed} local={locationState.view==='local'} flat={locationState.view==='map'} center={locationState} chunks={locationState.chunks} coordinates={locationState.coordinates} layer={locationState.layer as PreviewLayer} fog={false} solar={false} exaggeration={1} cycleDegrees={0} wireframe={wire} onPick={(x,y)=>select(x,y)} onStats={setStats}/>:<p role="status">Chargement du monde témoin…</p>}
 <p>Clic sur le sol : choisir une position · glisser : tourner · molette : zoom. Chunks de 32 × 32 cases. La croix orange marque la position choisie.</p>
 <p><a data-study-link href={'/terrain-study?'+new URLSearchParams({world:locationState.world,view:locationState.view,x:String(locationState.x),y:String(locationState.y),layer:locationState.layer,water:locationState.water?'1':'0',chunks:locationState.chunks?'1':'0',coordinates:locationState.coordinates?'1':'0'})}>Lien direct : {locationState.world} / {sector} / ({locationState.x}, {locationState.y}) / {locationState.view}</a></p>
 {stats&&<small data-study-stats>{stats.backend} · {stats.fps.toFixed(0)} FPS · {stats.draws} draws · {stats.residentVertices.toLocaleString('fr')} sommets résidents</small>}
 </main>;
}
